site_name: pDataService Documentation
site_description: Documentation for pDataService
site_author: Maatijaa
site_url: https://maatijaa.github.io/pdataservice-docs/

repo_name: Maatijaa/pdataservice-docs
repo_url: https://github.com/Maatijaa/pdataservice-docs
edit_uri: ""

theme:
  icon:
    logo: material/database
    repo: fontawesome/brands/git-alt
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started:
    - Installation: Getting Started/installation.md
    - Basic Usage: Getting Started/basic_usage.md
  - API: api.md
  - Development: dev_logs.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

copyright: |
  &copy; 2024 <a href="https://discord.gg/Hq5ZY87Hv3"  target="_blank" rel="noopener">ParaTron Softworks</a>